SchoolLib/Models/Books/AdditionalBook.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SchoolLib.Models.Books
{
	[DisplayName("Книга")]
	public class AdditionalBook : Book
	{
		[Required(ErrorMessage = "Необхідно надати мову книги")]
		[Display(Name = "Мова")]
		[StringLength(15, MinimumLength = 3, ErrorMessage = "Мова може мати від 3 до 15 символів")]
		public string Language { get; set; }

		[Required(ErrorMessage = "Необхідно надати шифр книги")]
		[Display(Name = "Шифр")]
		[StringLength(20, MinimumLength = 2, ErrorMessage = "Шифр книги може мати від 2 до 20 символів")]
		public string Cipher { get; set; }
	}
}

SchoolLib/Models/Books/ExternalBook.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SchoolLib.Models.Books
{
	[DisplayName("Незареєстрована книга")]
	public class ExternalBook : Book
	{
		[Required(ErrorMessage = "Необхідно надати жанр книги")]
		[Display(Name = "Жанр")]
		[StringLength(20, MinimumLength = 5, ErrorMessage = "Жанр книги може мати від 5 до 20 символів")]
		public string Genre { get; set; }
	}
}

SchoolLib/Controllers/InventoriesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolLib.Data;
using SchoolLib.Models.Books;

namespace SchoolLib.Controllers
{
	public class InventoriesController : Controller
	{
		private readonly List<SelectListItem> _bookTypeDropdownList;
		private readonly ApplicationDbContext _context;

		public InventoriesController(ApplicationDbContext context)
		{
			_context = context;

			_bookTypeDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Всі", Value = "Book", Selected = true},
				new SelectListItem {Text = "Підручники", Value = "StudyBook", Selected = false},
				new SelectListItem {Text = "Додаткова література", Value = "AdditionalBook", Selected = false}
			};
		}

		// GET: Inventories
		public async Task<IActionResult> Index()
		{
			var applicationDbContext = _context.Inventories.Include(i => i.Book);

			ViewData["bookTypesList"] = _bookTypeDropdownList;

			ViewBag.InvCount = await _context.Inventories.CountAsync();
			ViewBag.StudyBooksInvCount = await _context.Inventories.CountAsync(i => i.Book.Discriminator == "StudyBook");
			ViewBag.AddBooksInvCount = await _context.Inventories.CountAsync(i => i.Book.Discriminator == "AdditionalBook");

			return View(await applicationDbContext.ToListAsync());
		}

		public async Task<IActionResult> Search
		(
			string type,
			int? bookId,
			short? year,
			int? actNumber,
			string couse,
			string note
		)
		{
			var inventories = _context.Inventories.Include(i => i.Book).AsQueryable();

			if (type != "Book")
				inventories = inventories.Where(i => i.Book.Discriminator == type);

			if (bookId.HasValue)
				inventories = inventories.Where(i => i.BookId == bookId);

			if (year.HasValue)
				inventories = inventories.Where(i => i.Year == year);

			if (actNumber.HasValue)
				inventories = inventories.Where(i => i.ActNumber == actNumber);

			if (!string.IsNullOrWhiteSpace(couse))
				inventories = inventories.Where(i => i.Couse == couse);

			if (!string.IsNullOrWhiteSpace(note))
				inventories = inventories.Where(i => i.Note == note);

			return PartialView("_Inventories", await inventories.ToListAsync());
		}

		// GET: Inventories/Details/5
		public async Task<IActionResult> Details(int? id, int? bookId)
		{
			if (id == null)
			{
				if (bookId != null)
					return RedirectToAction("Create", new {bookId});
				return NotFound();
			}

			var inventory = await _context.Inventories
				.Include(i => i.Book)
				.SingleOrDefaultAsync(m => m.Id == id);
			if (inventory == null)
				return NotFound();

			return View(inventory);
		}

		// GET: Inventories/Create
		[HttpGet]
		public IActionResult Create(int? bookId)
		{
			ViewData["BookId"] = bookId;
			return View();
		}

		// POST: Inventories/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,ActNumber,Year,Couse,Note,BookId")] Inventory inventory)
		{
			if (!_context.Books.Any(b => b.Id == inventory.BookId))
			{
				ModelState.AddModelError("BookId", "Книги з даним інвентарним номером не існує");
			}
			else if (_context.Inventories.Any(i => i.BookId == inventory.BookId))
			{
				ModelState.AddModelError("BookId", "Книга з даним інвентарним номером вже має інвентарний запис");
			}

			if (ModelState.IsValid)
			{
				inventory.Book = _context.Books.SingleOrDefault(b => b.Id == inventory.BookId);
				_context.Add(inventory);
				await _context.SaveChangesAsync();
				return RedirectToAction("Index");
			}

			ViewData["BookId"] = inventory.BookId;
			ViewData["Fail"] = true;

			return View(inventory);
		}

		// GET: Inventories/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var inventory = await _context.Inventories.SingleOrDefaultAsync(m => m.Id == id);
			if (inventory == null)
			{
				return NotFound();
			}
			return View(inventory);
		}

		// POST: Inventories/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, int curBookId,
			[Bind("Id,ActNumber,Year,Couse,Note,BookId")] Inventory inventory)
		{
			if (id != inventory.Id)
				return NotFound();

			if (!_context.Books.Any(b => b.Id == inventory.BookId))
				ModelState.AddModelError("BookId", "Книги з даним інвентарним номером не існує");

			if (_context.Inventories.Any(i => i.BookId == inventory.BookId && i.BookId != curBookId))
				ModelState.AddModelError("BookId", "Книга з даним інвентарним номером вже має інвентарний запис");

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(inventory);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!InventoryExists(inventory.Id))
						return NotFound();

					throw;
				}

				return RedirectToAction("Index");
			}

			inventory.BookId = curBookId;

			return View(inventory);
		}

		// GET: Inventories/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
				return NotFound();

			var inventory = await _context.Inventories
				.Include(i => i.Book)
				.SingleOrDefaultAsync(m => m.Id == id);

			if (inventory == null)
				return NotFound();

			return View(inventory);
		}

		// POST: Inventories/Delete/5
		[HttpPost]
		[ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var inventory = await _context.Inventories.SingleOrDefaultAsync(m => m.Id == id);
			_context.Inventories.Remove(inventory);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}

		private bool InventoryExists(int id)
		{
			return _context.Inventories.Any(e => e.Id == id);
		}
	}
}

SchoolLib/Controllers/ReadersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolLib.Data;
using SchoolLib.Models.People;

namespace SchoolLib.Controllers
{
	public class ReadersController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly List<SelectListItem> _readerStatusDropdownList;
		private readonly List<SelectListItem> _readerTypeDropdownList;

		public ReadersController(ApplicationDbContext context)
		{
			_context = context;

			_readerTypeDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Неважливо", Value = "Reader", Selected = true},
				new SelectListItem {Text = "Учень", Value = "Student", Selected = false},
				new SelectListItem {Text = "Співробітник", Value = "Worker", Selected = false}
			};

			_readerStatusDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Неважливо", Value = "Any", Selected = true},
				new SelectListItem {Text = "Активний", Value = "Enabled", Selected = false},
				new SelectListItem {Text = "Деактивований", Value = "Disabled", Selected = false},
				new SelectListItem {Text = "Вибув", Value = "Removed", Selected = false}
			};
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			ViewData["readerTypeList"] = _readerTypeDropdownList;
			ViewData["readerStatusList"] = _readerStatusDropdownList;

			ViewBag.StudentsCount = await _context.Students.CountAsync();
			ViewBag.WorkersCount = await _context.Workers.CountAsync();
			ViewBag.ReadersCount = await _context.Readers.CountAsync();

			return View();
		}

		public async Task<IActionResult> SearchActions(
			string type,
			int? id,
			string firstName,
			string surName,
			string patronimic,
			string street,
			string house,
			short? apartment,
			string note,
			ReaderStatus status,
			string actn)
		{
			List<Reader> readersList;
			var readers = _context.Readers.Where(r => status.HasFlag(r.Status));
			if (type != "Reader")
				readers = readers.Where(r => r.Discriminator == type);
			if (id.HasValue)
				readers = readers.Where(r => r.Id == id);
			if (!string.IsNullOrWhiteSpace(firstName))
				readers = readers.Where(r => r.FirstName == firstName);
			if (!string.IsNullOrWhiteSpace(surName))
				readers = readers.Where(r => r.SurName == surName);
			if (!string.IsNullOrWhiteSpace(patronimic))
				readers = readers.Where(r => r.Patronimic == patronimic);
			if (!string.IsNullOrWhiteSpace(street))
				readers = readers.Where(r => r.Street == street);
			if (!string.IsNullOrWhiteSpace(house))
				readers = readers.Where(r => r.House == house);
			if (apartment.HasValue)
				readers = readers.Where(r => r.Apartment == apartment);
			if (!string.IsNullOrWhiteSpace(note))
				readers = readers.Where(r => r.Note == note);

			ViewData["type"] = type == "Reader" ? typeof(Reader) : type == "Student" ? typeof(Student) : typeof(Worker);
			if (actn == "activate")
			{
				readersList = await readers.Where(r => r.Status == ReaderStatus.Disabled).ToListAsync();
				foreach (var r in readersList)
				{
					r.Status = ReaderStatus.Enabled;
					r.LastRegistrationDate = DateTime.Today.ToString("dd.MM.yyyy");
				}
				_context.UpdateRange(readersList);
				await _context.SaveChangesAsync();
			}
			else if (actn == "restore")
			{
				readersList = await readers.Where(r => r.Status == ReaderStatus.Removed).ToListAsync();
				foreach (var r in readersList)
				{
					r.Drop.Note = $"Відновлений {DateTime.Today.ToString("dd.MM.yyyy")}";
					r.Status = ReaderStatus.Disabled;
					r.LastRegistrationDate = DateTime.Today.ToString("dd.MM.yyyy");
				}
				_context.UpdateRange(readersList);
				await _context.SaveChangesAsync();
			}
			readersList = await readers.ToListAsync();
			return PartialView("_Readers", readersList);
		}

		public async Task<IActionResult> Activate(
			string type,
			int? id,
			string firstName,
			string surName,
			string patronimic,
			string street,
			string house,
			short? apartment,
			string lastRegDate,
			string firstRegDate,
			string note,
			ReaderStatus status)
		{
			var readers = _context.Readers.Where(r => status.HasFlag(r.Status));
			if (type != "Reader")
				readers = readers.Where(r => r.Discriminator == type);
			if (id.HasValue)
				readers = readers.Where(r => r.Id == id);
			if (!string.IsNullOrWhiteSpace(firstName))
				readers = readers.Where(r => r.FirstName == firstName);
			if (!string.IsNullOrWhiteSpace(surName))
				readers = readers.Where(r => r.SurName == surName);
			if (!string.IsNullOrWhiteSpace(patronimic))
				readers = readers.Where(r => r.Patronimic == patronimic);
			if (!string.IsNullOrWhiteSpace(street))
				readers = readers.Where(r => r.Street == street);
			if (!string.IsNullOrWhiteSpace(house))
				readers = readers.Where(r => r.House == house);
			if (apartment.HasValue)
				readers = readers.Where(r => r.Apartment == apartment);
			/* !todo:Исправить сравнение строк на сравнение дат */
			if (!string.IsNullOrWhiteSpace(lastRegDate))
				readers = readers.Where(r => r.LastRegistrationDate == lastRegDate);
			if (!string.IsNullOrWhiteSpace(firstRegDate))
				readers = readers.Where(r => r.FirstRegistrationDate == firstRegDate);
			/* !todo */
			if (!string.IsNullOrWhiteSpace(note))
				readers = readers.Where(r => r.Note == note);

			var view = "";

			return PartialView(view, await readers.ToListAsync());
		}

		// GET: Readers/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var reader = await _context.Readers
				.SingleOrDefaultAsync(m => m.Id == id);
			if (reader == null)
			{
				return NotFound();
			}
			if (reader.Discriminator == "Student")
			{
				return RedirectToAction("Details", "Students", new {id});
			}

			return RedirectToAction("Details", "Workers", new {id});
		}

		// GET: Readers/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var reader = await _context.Readers.SingleOrDefaultAsync(m => m.Id == id);
			if (reader == null)
			{
				return NotFound();
			}
			if (reader.Discriminator == "Student")
			{
				return RedirectToAction("Edit", "Students", new {id});
			}

			return RedirectToAction("Edit", "Workers", new {id});
		}

		// GET: Readers/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var reader = await _context.Readers
				.SingleOrDefaultAsync(m => m.Id == id);
			if (reader == null)
			{
				return NotFound();
			}
			if (reader.Discriminator == "Student")
			{
				return RedirectToAction("Delete", "Students", new {id});
			}

			return RedirectToAction("Delete", "Workers", new {id});
		}

		private bool ReaderExists(int id)
		{
			return _context.Readers.Any(e => e.Id == id);
		}
	}
}

SchoolLib/Controllers/StudyBooksController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SchoolLib.Data;
using SchoolLib.Models.Books;

namespace SchoolLib.Controllers
{
	public class StudyBooksController : Controller
	{
		private readonly ApplicationDbContext _context;

		public StudyBooksController(ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: StudyBooks/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
				return NotFound();

			var studyBook = await _context.StudyBooks
				.Include(sb => sb.Inventory)
				.Include(sb => sb.Provenance)
				.SingleOrDefaultAsync(m => m.Id == id);
			if (studyBook == null)
				return NotFound();

			if (studyBook.Status == BookStatus.OnHands)
			{
				ViewData["readerId"] =
					_context.Issuances.Where(i => i.BookId == studyBook.Id && i.AcceptanceDate == null).SingleOrDefaultAsync()?.Result
						.ReaderId;
			}
			return View(studyBook);
		}

		// GET: StudyBooks/Create
		public IActionResult Create()
		{
			ViewBag.FreeId = _context.Books.Max(sb => sb.Id) + 1;

			return View();
		}

		// POST: StudyBooks/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(
			[Bind("Id,Name,Author,AuthorCipher,Grade,Subject,Published,Price,Note")] StudyBook studyBook
		)
		{
			if (_context.Books.Any(b => b.Id == studyBook.Id))
			{
				ModelState.AddModelError("Id", "Підручник з даним інвентарним номером все існує");
			}
			if (ModelState.IsValid)
			{
				studyBook.Status = BookStatus.InStock;
				_context.Add(studyBook);
				await _context.SaveChangesAsync();
				return RedirectToAction("Index", "Books");
			}
			return View(studyBook);
		}

		// GET: StudyBooks/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var studyBook = await _context.StudyBooks.SingleOrDefaultAsync(m => m.Id == id);
			if (studyBook == null)
			{
				return NotFound();
			}
			return View(studyBook);
		}

		// POST: StudyBooks/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(
			int curId,
			[Bind("Id,Name,Author,AuthorCipher,Grade,Subject,Published,Price,Note,Status")] StudyBook studyBook
		)
		{
			if (_context.Books.Any(b => b.Id == studyBook.Id && b.Id != curId))
			{
				ModelState.AddModelError("Id", "Підручник з даним інвентарним номером все існує");
			}
			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(studyBook);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!StudyBookExists(studyBook.Id))
					{
						//!todo: Сделать возможным изменение ид книги
						//await DeleteConfirmed(curId);
						//return await Create(studyBook);
						return NotFound();
					}
					throw;
				}
				return RedirectToAction("Index", "Books");
			}
			studyBook.Id = curId;
			return View(studyBook);
		}

		// GET: StudyBooks/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var studyBook = await _context.StudyBooks
				.SingleOrDefaultAsync(m => m.Id == id);
			if (studyBook == null)
			{
				return NotFound();
			}

			return View(studyBook);
		}

		// POST: StudyBooks/Delete/5
		[HttpPost]
		[ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var studyBook = await _context.StudyBooks.SingleOrDefaultAsync(m => m.Id == id);
			_context.StudyBooks.Remove(studyBook);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index", "Books");
		}

		private bool StudyBookExists(int id)
		{
			return _context.StudyBooks.Any(e => e.Id == id);
		}
	}
}

SchoolLib/Views/Statistic/Index.cshtml
@{
	ViewData["Title"] = "Статистика";
}

<h2>@ViewData["Title"]</h2>

<div class="form-horizontal row">
	<div class="form-horizontal col-md-6">
		<div class="form-horizontal row">
			<a asp-controller="Inventories" asp-action="Index" class="col-md-6 btn btn-default">Інвентаризація книг</a>
			<a asp-controller="Provenances" asp-action="Index" class="col-md-6 btn btn-default">Походження книг</a>
		</div>
		<hr />
		<div class="form-horizontal row">
			<a asp-controller="AdditionalBooks" asp-action="Create" class="col-md-6 btn btn-default">Додати нову книгу</a>
			<a asp-controller="StudyBooks" asp-action="Create" class="col-md-6 btn btn-default">Додати новий підручник</a>
		</div>
	</div>
	<div class="form-horizontal col-md-6">
		<div class="form-horizontal row">
			<label class="col-md-12 col-md-pull-4 control-label">Кількість підручників у бібліотеці: @ViewBag.StudyBooksCount</label>
			<label class="col-md-12 col-md-pull-4 control-label">Кількість інших книг у бібліотеці: @ViewBag.AddBooksCount</label>
			<label class="col-md-12 col-md-pull-4 control-label">Кількість книг у бібліотеці загалом: @ViewBag.BooksCount</label>
		</div>
	</div>
</div>
<hr />


<div class="form-horizontal row">
	<div class="col-md-4">
		<div class="form-group">
			<label class="col-md-4 control-label">Тип</label>
			<div class="col-md-8">
				<select asp-items="ViewBag.bookTypesList" class="form-control" id="type"></select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-4 control-label">Статус</label>
			<div class="col-md-8">
				<select asp-items="ViewBag.bookStatusList" class="form-control" id="status"></select>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="form-group">
			<div class="col-md-12">
				<input type="number" name="id" id="id" placeholder="Інвентарний №..." class="form-control" />
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-12">
				<input type="text" name="name" id="name" placeholder="Назва..." class="form-control" />
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="form-group">
			<div class="col-md-12">
				<input type="text" name="author" id="author" placeholder="Автор..." class="form-control" />
			</div>
		</div>
	</div>
</div>
<div class="form-group col-md-offset-5 col-md-7">
	<input type="submit" id="submit" name="search" value="Пошук" class="btn btn-default" />
</div>

<div id="results"></div>
<br />
<br />
<br />
<br />

@section Scripts {
	<script type="text/javascript">
		$(document).ready(function() {
			$('#submit').click(function(e) {
				e.preventDefault();
				var id = encodeURIComponent($('#id').val());
				var name = encodeURIComponent($('#name').val());
				var author = encodeURIComponent($('#author').val());
				var type = encodeURIComponent($('#type').val());
				var status = encodeURIComponent($('#status').val());

				$('#results').load('@Url.Action("Search")?type=' +
					type +
					'&id=' +
					id +
					'&name=' +
					name +
					'&author=' +
					author +
					'&status=' +
					status);
			});
		});
	</script>
}

SchoolLib/Views/Statistic/_ReadersAcc.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

SchoolLib/Views/Statistic/_ReadersDrop.cshtml
@model SchoolLib.Models.StatisticViewModels.ReadersStatisticViewModel

<div>
    <h4>Кількість читачів, що вибули</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>Всього:</dt>
        <dd>@Model.Students.Count + @Model.Workers.Count</dd>

        <dt>@Html.DisplayNameFor(model => model.Cipher)</dt>
        <dd>@Html.DisplayFor(model => model.Cipher)</dd>

        <dt>@Html.DisplayNameFor(model => model.Author)</dt>
        <dd>@Html.DisplayFor(model => model.Author)</dd>

        <dt>@Html.DisplayNameFor(model => model.AuthorCipher)</dt>
        <dd>@Html.DisplayFor(model => model.AuthorCipher)</dd>

        <dt>@Html.DisplayNameFor(model => model.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Name)</dd>

        <dt>@Html.DisplayNameFor(model => model.Published)</dt>
        <dd>@Html.DisplayFor(model => model.Published)</dd>

        <dt>@Html.DisplayNameFor(model => model.Price)</dt>
        <dd>@Html.DisplayFor(model => model.Price)</dd>

        <dt>@Html.DisplayNameFor(model => model.Language)</dt>
        <dd>@Html.DisplayFor(model => model.Language)</dd>

        <dt>@Html.DisplayNameFor(model => model.Note)</dt>
        <dd>@Html.DisplayFor(model => model.Note)</dd>

        <dt>@Html.DisplayNameFor(model => model.Status)</dt>
        <dd>
            @if (ViewBag.readerId != null)
            {
                <a asp-controller="Readers" asp-action="Details" asp-route-id="@ViewBag.readerId">
                    @Html.DisplayFor(model => model.Status)
                </a>
            }
            else
            {
                @Html.DisplayFor(model => model.Status)
            }
        </dd>
    </dl>
</div>