SchoolLib/Models/People/Reader.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SchoolLib.Data.Validators;

namespace SchoolLib.Models.People
{
	[Flags]
	[DisplayName("Статус читача")]
	public enum ReaderStatus
	{
		[Display(Name = "Активний")] Enabled = 1,
		[Display(Name = "Деактивований")] Disabled = 2,
		[Display(Name = "Вибув")] Removed = 4,
		[Display(Name = "Будь-який")] Any = Enabled | Disabled | Removed
	}

	[Table("Readers")]
	[DisplayName("Читач")]
	public abstract class Reader
	{
		[Required(ErrorMessage = "Необхідно надати ідентифікаційний номер")]
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.None)]
		[Column("ReaderId")]
		[Display(Name = "Ідентифікаційний №")]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:D6}")]
		[Range(1, 100000, ErrorMessage = "Ідентифікаційний номер має можливий діапазон від {1} до {2}")]
		public int Id { get; set; }

		[Required(ErrorMessage = "Необхідно надати ім'я")]
		[Display(Name = "Ім'я")]
		[StringLength(15, MinimumLength = 2, ErrorMessage = "Ім'я повинно містити від 2 до 15 символів")]
		public string FirstName { get; set; }

		[Required(ErrorMessage = "Необхідно надати призвіще")]
		[Display(Name = "Прізвище")]
		[StringLength(20, MinimumLength = 2, ErrorMessage = "Призвіще повинно містити від 2 до 20 символів")]
		public string SurName { get; set; }

		[Required(ErrorMessage = "Необхідно заповнити поле ім'я по-батькові")]
		[Display(Name = "По-батькові")]
		[StringLength(25, MinimumLength = 2, ErrorMessage = "По-батькові повинно містити від 2 до 25 символів")]
		public string Patronimic { get; set; }

		[Required(ErrorMessage = "Необхідно надати назву вулиці")]
		[Display(Name = "Вулиця")]
		[StringLength(25, MinimumLength = 3, ErrorMessage = "Назва вулиці повинна містити від 3 до 25 символів")]
		public string Street { get; set; }

		[Required(ErrorMessage = "Необхідно надати номер дому")]
		[Display(Name = "Дім")]
		[StringLength(8, MinimumLength = 1, ErrorMessage = "Номер дому повинен містити від 1 до 8 символів")]
		public string House { get; set; }

		[Display(Name = "Квартира")]
		[Range(1, 1000, ErrorMessage = "Номер квартири має діапазон значеннь від {1} до {2}")]
		public short? Apartment { get; set; }

		[Required(ErrorMessage = "Необхідно надати дату реєстрації")]
		[Display(Name = "Дата реєстрації")]
		[StringLength(10, ErrorMessage = "Некоректний формат дати")]
		[DateRange("-12")]
		public string FirstRegistrationDate { get; set; }

		[Required(ErrorMessage = "Необхідно надати дату перереєстрації")]
		[Display(Name = "Дата перереєстрації")]
		[StringLength(10, ErrorMessage = "Некоректний формат дати")]
		[DateRange("-12")]
		public string LastRegistrationDate { get; set; }

		[Display(Name = "Тип")]
		[StringLength(30)]
		public string Discriminator { get; set; }

		[Display(Name = "Примітка")]
		[StringLength(250, ErrorMessage = "Опис читача не може містити більше 250 символів")]
		public string Note { get; set; }

		[Required]
		[Display(Name = "Статус")]
		public ReaderStatus Status { get; set; }

		[Display(Name = "Вибуття")]
		public Drop Drop { get; set; }
	}
}

SchoolLib/Controllers/DropsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolLib.Data;
using SchoolLib.Models.People;

namespace SchoolLib.Controllers
{
	public class DropsController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly List<SelectListItem> _readerTypeDropdownList;

		public DropsController(ApplicationDbContext context)
		{
			_context = context;
			_readerTypeDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Неважливо", Value = "Reader", Selected = true},
				new SelectListItem {Text = "Учень", Value = "Student", Selected = false},
				new SelectListItem {Text = "Співробітник", Value = "Worker", Selected = false}
			};
		}

		public async Task<IActionResult> Index()
		{
			var applicationDbContext = _context.Drops.Include(d => d.Reader);

			ViewData["readerTypeList"] = _readerTypeDropdownList;
			ViewBag.DropsCount = await _context.Drops.CountAsync();
			ViewBag.StudentsDropsCount = await _context.Drops.CountAsync(d => d.Reader.Discriminator.Equals("Student"));
			ViewBag.WorkersDropsCount = await _context.Drops.CountAsync(d => d.Reader.Discriminator.Equals("Worker"));

			return View(await applicationDbContext.ToListAsync());
		}

		public async Task<IActionResult> Search
		(
			string type,
			int? readerId,
			string date,
			string couse,
			string note
		)
		{
			var drops = _context.Drops.Include(d => d.Reader).AsQueryable();

			if (type != "Reader")
				drops = drops.Where(d => d.Reader.Discriminator == type);

			if (readerId.HasValue)
				drops = drops.Where(d => d.ReaderId == readerId);

			if (!string.IsNullOrWhiteSpace(date))
				drops = drops.Where(d => d.Date == date);

			if (!string.IsNullOrWhiteSpace(couse))
				drops = drops.Where(d => d.Couse == couse);

			if (!string.IsNullOrWhiteSpace(note))
				drops = drops.Where(d => d.Note == note);

			return PartialView("_Drops", await drops.ToListAsync());
		}

		public async Task<IActionResult> Details(int? id, int? readerId)
		{
			if (id == null)
			{
				if (readerId != null)
					return RedirectToAction("Create", new {readerId});
				return NotFound();
			}
			var drop = await _context.Drops
				.Include(d => d.Reader)
				.SingleOrDefaultAsync(m => m.Id == id);
			if (drop == null)
				return NotFound();
			return View(drop);
		}

		[HttpGet]
		public IActionResult Create(int? readerId)
		{
			Reader reader =
				_context.Students.SingleOrDefault(r => r.Id == readerId) ??
				(Reader) _context.Workers.SingleOrDefault(r => r.Id == readerId);

			ViewData["Reader"] = reader;
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Date,Couse,Note,ReaderId")] Drop drop)
		{
			if (!_context.Readers.Any(b => b.Id == drop.ReaderId))
			{
				ModelState.AddModelError("ReaderId", "Читача з даним ідентифікаційним номером не існує");
				ViewData["Fail"] = true;
			}
			else if (_context.Drops.Any(d => d.ReaderId == drop.ReaderId))
			{
				ModelState.AddModelError("ReaderId", "Читач з даним ідентифікаційним номером вже має запис про вибуття");
				ViewData["Fail"] = true;
			}
			if (ModelState.IsValid)
			{
				_context.Add(drop);
				await _context.SaveChangesAsync();
				await DropReader(drop.ReaderId);
				return RedirectToAction("Index");
			}
			ViewData["ReaderId"] = drop.ReaderId;
			return View(drop);
		}

		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
				return NotFound();
			var drop = await _context.Drops.SingleOrDefaultAsync(m => m.Id == id);
			if (drop == null)
				return NotFound();
			ViewData["ReaderId"] = drop.ReaderId;
			return View(drop);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit
		(
			int id,
			int curReaderId,
			[Bind("Id,Date,Couse,Note,ReaderId")] Drop drop
		)
		{
			if (id != drop.Id)
				return NotFound();
			if (!_context.Readers.Any(b => b.Id == drop.ReaderId))
				ModelState.AddModelError("ReaderId", "Читача з даним ідентифікаційним номером не існує");
			else if (_context.Drops.Any(d => d.ReaderId == drop.ReaderId && d.ReaderId != curReaderId))
				ModelState.AddModelError("ReaderId", "Читач з даним ідентифікаційним номером вже має запис про вибуття");
			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(drop);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!DropExists(drop.Id))
						return NotFound();
					throw;
				}
				return RedirectToAction("Index");
			}
			drop.ReaderId = curReaderId;
			return View(drop);
		}

		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
				return NotFound();
			var drop = await _context.Drops
				.Include(d => d.Reader)
				.SingleOrDefaultAsync(m => m.Id == id);
			if (drop == null)
				return NotFound();
			return View(drop);
		}

		[HttpPost]
		[ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var drop = await _context.Drops.SingleOrDefaultAsync(m => m.Id == id);
			_context.Drops.Remove(drop);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}

		private bool DropExists(int id)
		{
			return _context.Drops.Any(e => e.Id == id);
		}

		private async Task<int> DropReader(int id)
		{
			var reader = await _context.Readers.Include(d => d.Drop)
				.SingleOrDefaultAsync(m => m.Id == id);
			reader.Status = ReaderStatus.Removed;
			_context.Update(reader);
			return await _context.SaveChangesAsync();
		}
	}
}

SchoolLib/Controllers/StudentsController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SchoolLib.Data;
using SchoolLib.Models.People;

namespace SchoolLib.Controllers
{
	public class StudentsController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly IFormatProvider culture = new CultureInfo("uk-UA");

		public StudentsController(ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: Students
		public IActionResult Index()
		{
			return RedirectToAction("Index", "Readers");
			//return View(await _context.Students.ToListAsync());
		}

		// GET: Students/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
				return NotFound();

			var student = await _context.Students.Include(s => s.Drop)
				.SingleOrDefaultAsync(m => m.Id == id);
			if (student == null)
				return NotFound();

			return View(student);
		}

		// GET: Students/Create
		public IActionResult Create()
		{
			ViewData["FirstRegistrationDate"] = ViewData["LastRegistrationDate"] = DateTime.Today.ToString("dd.MM.yyyy");
			ViewBag.FreeId = _context.Readers.Max(s => s.Id) + 1;

			return View();
		}

		// POST: Students/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create
		(
			[Bind(
				"Id,FirstName,SurName,Patronimic,Street,House,Apartment,Grade,FirstRegistrationDate,LastRegistrationDate,Note")]
			Student student
		)
		{
			if (_context.Readers.Any(s => s.Id == student.Id))
				ModelState.AddModelError("Id", "Учень з даним ідентифікаційним номером все існує");
			if (ModelState.IsValid && DateTime.ParseExact(student.FirstRegistrationDate, "dd.MM.yyyy", culture) >
			    DateTime.ParseExact(student.LastRegistrationDate, "dd.MM.yyyy", culture))
			{
				ModelState.AddModelError("LastRegistrationDate", "Дата перереєстрації не може бути раніше ніж дата реєстрації");
			}
			if (ModelState.IsValid)
			{
				student.LastRegistrationDate = student.FirstRegistrationDate;
				student.Status = ReaderStatus.Enabled;
				_context.Add(student);
				await _context.SaveChangesAsync();
				return RedirectToAction("Index", "Readers");
			}
			return View(student);
		}

		// GET: Students/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var student = await _context.Students.SingleOrDefaultAsync(m => m.Id == id);
			if (student == null)
			{
				return NotFound();
			}
			return View(student);
		}

		// POST: Students/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit
		(
			int curId,
			[Bind(
				"Id,FirstName,SurName,Patronimic,Street,House,Apartment,Grade,FirstRegistrationDate,LastRegistrationDate,Status,Note")]
			Student student
		)
		{
			if (curId != student.Id)
				return NotFound();

			if (_context.Readers.Any(s => s.Id == student.Id && s.Id != curId))
				ModelState.AddModelError("Id", "Учень з даним ідентифікаційним номером все існує");
			if (ModelState.IsValid && DateTime.ParseExact(student.FirstRegistrationDate, "dd.MM.yyyy", culture) >
			    DateTime.ParseExact(student.LastRegistrationDate, "dd.MM.yyyy", culture))
			{
				ModelState.AddModelError("LastRegistrationDate", "Дата перереєстрації не може бути раніше ніж дата реєстрації");
			}
			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(student);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!StudentExists(student.Id))
					{
						return NotFound();
					}
					throw;
				}
				return RedirectToAction("Index", "Readers");
			}
			student.Id = curId;
			return View(student);
		}

		// GET: Students/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var student = await _context.Students
				.SingleOrDefaultAsync(m => m.Id == id);
			if (student == null)
			{
				return NotFound();
			}

			return View(student);
		}

		// POST: Students/Delete/5
		[HttpPost]
		[ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var student = await _context.Students.SingleOrDefaultAsync(m => m.Id == id);
			_context.Students.Remove(student);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}

		private bool StudentExists(int id)
		{
			return _context.Students.Any(e => e.Id == id);
		}
	}
}

SchoolLib/Controllers/WorkersController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SchoolLib.Data;
using SchoolLib.Models.People;

namespace SchoolLib.Controllers
{
	public class WorkersController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly IFormatProvider _culture = new CultureInfo("uk-UA");

		public WorkersController(ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: Workers
		public IActionResult Index()
		{
			return RedirectToAction("Index", "Readers");
		}

		// GET: Workers/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var worker = await _context.Workers.Include(w => w.Drop)
				.SingleOrDefaultAsync(m => m.Id == id);
			if (worker == null)
			{
				return NotFound();
			}

			return View(worker);
		}

		// GET: Workers/Create
		public IActionResult Create()
		{
			ViewData["FirstRegistrationDate"] = ViewData["LastRegistrationDate"] = DateTime.Today.ToString("dd.MM.yyyy");
			ViewBag.FreeId = _context.Readers.Max(w => w.Id) + 1;

			return View();
		}

		// POST: Workers/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create
		(
			[Bind(
				"Id,FirstName,SurName,Patronimic,Street,House,Apartment,Position,FirstRegistrationDate,LastRegistrationDate,Note")]
			Worker worker
		)
		{
			if (_context.Readers.Any(w => w.Id == worker.Id))
				ModelState.AddModelError("Id", "Співробітник з даним ідентифікаційним номером все існує");
			if (ModelState.IsValid)
			{
				worker.LastRegistrationDate = worker.FirstRegistrationDate;
				worker.Status = ReaderStatus.Enabled;
				_context.Add(worker);
				await _context.SaveChangesAsync();
				return RedirectToAction("Index", "Readers");
			}
			return View(worker);
		}

		// GET: Workers/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var worker = await _context.Workers.SingleOrDefaultAsync(m => m.Id == id);
			if (worker == null)
			{
				return NotFound();
			}
			return View(worker);
		}

		// POST: Workers/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit
		(
			int curId,
			[Bind(
				"Id,FirstName,SurName,Patronimic,Street,House,Apartment,Position,FirstRegistrationDate,LastRegistrationDate,Status,Note")]
			Worker worker
		)
		{
			if (curId != worker.Id)
				return BadRequest();

			if (_context.Readers.Any(w => w.Id == worker.Id && w.Id != curId))
				ModelState.AddModelError("Id", "Співробітник з даним ідентифікаційним номером все існує");
			if (ModelState.IsValid &&
			    DateTime.ParseExact(worker.FirstRegistrationDate, "dd.MM.yyyy", _culture) >
			    DateTime.ParseExact(worker.LastRegistrationDate, "dd.MM.yyyy", _culture))
			{
				ModelState.AddModelError("LastRegistrationDate", "Дата перереєстрації не може бути раніше ніж дата реєстрації");
			}
			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(worker);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!WorkerExists(worker.Id))
						return NotFound();
					throw;
				}
				return RedirectToAction("Index", "Readers");
			}
			worker.Id = curId;
			return View(worker);
		}

		// GET: Workers/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var worker = await _context.Workers
				.SingleOrDefaultAsync(m => m.Id == id);
			if (worker == null)
			{
				return NotFound();
			}

			return View(worker);
		}

		// POST: Workers/Delete/5
		[HttpPost]
		[ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var worker = await _context.Workers.SingleOrDefaultAsync(m => m.Id == id);
			_context.Workers.Remove(worker);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}

		private bool WorkerExists(int id)
		{
			return _context.Workers.Any(e => e.Id == id);
		}
	}
}

SchoolLib/Views/Readers/Index.cshtml
@{
	ViewData["Title"] = "Читачі";
}

<h2>@ViewData["Title"]</h2>

<div class="form-horizontal row">
	<div class="form-horizontal col-md-6">
		<div class="form-horizontal row">
			<a asp-controller="Drops" asp-action="Index" class="col-md-12 btn btn-default">Вибуття</a>
		</div>
		<hr />
		<div class="form-horizontal row">
			<a asp-controller="Students" asp-action="Create" class="col-md-6 btn btn-default">Додати учня</a>
			<a asp-controller="Workers" asp-action="Create" class="col-md-6 btn btn-default">Додати співробітника</a>
		</div>
	</div>
	<div class="form-horizontal col-md-6">
		<div class="form-horizontal row">
			<label class="col-md-12 col-md-pull-4 control-label">Кількість учнів у бібліотеці: @ViewBag.StudentsCount</label>
			<label class="col-md-12 col-md-pull-4 control-label">Кількість співробітників у бібліотеці: @ViewBag.WorkersCount</label>
			<label class="col-md-12 col-md-pull-4 control-label">Кількість читачів у бібліотеці загалом: @ViewBag.ReadersCount</label>
		</div>
	</div>
</div>
<hr/>

<div class="form-horizontal row">
	<div class="col-md-4">
		<div class="form-group">
			<label class="col-md-4 control-label">Тип</label>
			<div class="col-md-8">
				<select asp-items="ViewBag.readerTypeList" class="form-control" id="type"></select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-4 control-label">Статус</label>
			<div class="col-md-8">
				<select asp-items="ViewBag.readerStatusList" class="form-control" id="status"></select>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="form-group">
			<div class="col-md-12">
				<input type="number" name="id" id="id" placeholder="Ідентифікаційний №..." class="form-control"/>
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-12">
				<input type="text" name="surName" id="surName" placeholder="Прізвище..." class="form-control"/>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="form-group">
			<div class="col-md-12">
				<input type="text" name="firstName" id="firstName" placeholder="Ім'я..." class="form-control"/>
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-12">
				<input type="text" name="patronimic" id="patronimic" placeholder="По-батькові..." class="form-control"/>
			</div>
		</div>
	</div>
</div>
<div class="form-group row">
	<div class="col-md-offset-3 col-md-3">
		<input type="submit" id="submit" name="search" value="Пошук" class="btn btn-default"/>
	</div>
	<div class="col-md-6">
		<input type="submit" id="submit" name="activate" value="Активувати читачів" class="btn btn-default"/>
	</div>
</div>

<div id="results"></div>
<br/>
<br/>
<br/>
<br/>

@section Scripts {
	<script type="text/javascript">
		$(document).ready(function() {
			$('#submit').click(function(e) {
				e.preventDefault();
				var id = encodeURIComponent($('#id').val());
				var firstName = encodeURIComponent($('#firstName').val());
				var surName = encodeURIComponent($('#surName').val());
				var patronimic = encodeURIComponent($('#patronimic').val());
				var type = encodeURIComponent($('#type').val());
				var status = encodeURIComponent($('#status').val());
				var actn = $(this).attr('name');

				$('#results').load('@Url.Action("SearchActions")?type=' +
					type +
					'&id=' +
					id +
					'&firstName=' +
					firstName +
					'&surName=' +
					surName +
					'&patronimic=' +
					patronimic +
					'&status=' +
					status +
					'&actn=' +
					actn);
			});
		});
	</script>
}

SchoolLib/Views/Readers/_Readers.cshtml
@using SchoolLib.Models.People
@model IEnumerable<SchoolLib.Models.People.Reader>

<table class="table  table-bordered table-hover">
    <thead>
    <tr>
        <th>@Html.DisplayNameFor(model => model.Id)</th>
        <th>@Html.DisplayNameFor(model => model.SurName)</th>
        <th>@Html.DisplayNameFor(model => model.FirstName)</th>
        <th>@Html.DisplayNameFor(model => model.Patronimic)</th>
        @if (ViewBag.type == typeof(Student))
        {
            <th>@Html.DisplayNameFor(model => ((Student) model).Grade)</th>
        }
        else if (ViewBag.type == typeof(Worker))
        {
            <th>@Html.DisplayNameFor(model => ((Worker) model).Position)</th>
        }
        else
        {
            <th>Посада/Клас</th>
            <th>@Html.DisplayNameFor(model => model.Discriminator)</th>
        }
        <th>@Html.DisplayNameFor(model => model.Status)</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Id)</td>
            <td>@Html.DisplayFor(modelItem => item.SurName)</td>
            <td>@Html.DisplayFor(modelItem => item.FirstName)</td>
            <td>@Html.DisplayFor(modelItem => item.Patronimic)</td>
            @if (ViewBag.type == typeof(Student))
            {
                <td>@Html.DisplayFor(modelItem => ((Student) item).Grade)</td>
            }
            else if (ViewBag.type == typeof(Worker))
            {
                <td>@Html.DisplayFor(modelItem => ((Worker) item).Position)</td>
            }
            else if (item.Discriminator == "Student")
            {
                <td>@Html.DisplayFor(modelItem => ((Student) item).Grade)</td>
                <td>Учень</td>
            }
            else
            {
                <td>@Html.DisplayFor(modelItem => ((Worker) item).Position)</td>
                <td>Співробітник</td>
            }
            <td>@Html.DisplayFor(modelItem => item.Status)</td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Редагувати</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Деталі</a> |
                <a asp-controller="Issuances" asp-action="Index" asp-route-readerId="@item.Id">Формуляр</a>
            </td>
        </tr>
    }
    </tbody>
</table>