SchoolLib/Models/Books/StudyBook.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SchoolLib.Models.Books
{
	[DisplayName("Підручник")]
	public class StudyBook : Book
	{
		[Required(ErrorMessage = "Необхідно надати номер класу")]
		[Display(Name = "Клас")]
		[Range(1, 12, ErrorMessage = "Клас має можливий діапазон від {1} до {2}")]
		public byte Grade { get; set; }

		[Required(ErrorMessage = "Необхідно надати назву предмету")]
		[Display(Name = "Предмет")]
		[StringLength(20, MinimumLength = 4, ErrorMessage = "Предмет може мати від 4 до 20 символів")]
		public string Subject { get; set; }
	}
}

SchoolLib/Controllers/BooksController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolLib.Data;
using SchoolLib.Models.Books;

namespace SchoolLib.Controllers
{
	public class BooksController : Controller
	{
		private readonly List<SelectListItem> _bookStatusDropdownList;
		private readonly List<SelectListItem> _bookTypeDropdownList;
		private readonly ApplicationDbContext _context;

		public BooksController(ApplicationDbContext context)
		{
			_context = context;

			_bookTypeDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Всі", Value = "Book", Selected = true},
				new SelectListItem {Text = "Підручники", Value = "StudyBook", Selected = false},
				new SelectListItem {Text = "Додаткова література", Value = "AdditionalBook", Selected = false}
			};

			_bookStatusDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Неважливо", Value = "Any", Selected = true},
				new SelectListItem {Text = "В бібліотеці", Value = "InStock", Selected = false},
				new SelectListItem {Text = "У читача", Value = "OnHands", Selected = false}
			};
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			ViewData["bookTypesList"] = _bookTypeDropdownList;
			ViewData["bookStatusList"] = _bookStatusDropdownList;

			ViewBag.BooksCount = await _context.Books.CountAsync();
			ViewBag.AddBooksCount = await _context.AdditionalBooks.CountAsync();
			ViewBag.StudyBooksCount = await _context.StudyBooks.CountAsync();

			return View();
		}

		public async Task<IActionResult> Search(
			string type,
			int? id,
			string name,
			string author,
			BookStatus status)
		{
			var books = _context.Books.Where(b => status.HasFlag(b.Status));
			if (type != "Book")
				books = books.Where(b => b.Discriminator == type);
			if (id.HasValue)
				books = books.Where(b => b.Id == id);
			if (!string.IsNullOrWhiteSpace(name))
				books = books.Where(b => b.Name == name);
			if (!string.IsNullOrWhiteSpace(author))
				books = books.Where(b => b.Author == author);

			ViewData["type"] = type == "Book" ? typeof(Book) : type == "StudyBook" ? typeof(StudyBook) : typeof(AdditionalBook);

			return PartialView("_Books", await books.ToListAsync());
		}

		// GET: Books/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var book = await _context.Books
				.SingleOrDefaultAsync(m => m.Id == id);
			if (book == null)
			{
				return NotFound();
			}

			if (book.Discriminator == "AdditionalBook")
			{
				return RedirectToAction("Details", "AdditionalBooks", new {id});
			}

			return RedirectToAction("Details", "StudyBooks", new {id});
		}

		// GET: Readers/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var book = await _context.Books.SingleOrDefaultAsync(m => m.Id == id);

			if (book == null)
			{
				return NotFound();
			}

			if (book.Discriminator == "AdditionalBook")
			{
				return RedirectToAction("Edit", "AdditionalBooks", new {id});
			}

			return RedirectToAction("Edit", "StudyBooks", new {id});
		}

		// GET: Readers/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var book = await _context.Books.SingleOrDefaultAsync(m => m.Id == id);

			if (book == null)
			{
				return NotFound();
			}

			if (book.Discriminator == "AdditionalBook")
			{
				return RedirectToAction("Delete", "AdditionalBooks", new {id});
			}

			return RedirectToAction("Delete", "StudyBooks", new {id});
		}
	}
}

SchoolLib/Controllers/InventoriesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolLib.Data;
using SchoolLib.Models.Books;

namespace SchoolLib.Controllers
{
	public class InventoriesController : Controller
	{
		private readonly List<SelectListItem> _bookTypeDropdownList;
		private readonly ApplicationDbContext _context;

		public InventoriesController(ApplicationDbContext context)
		{
			_context = context;

			_bookTypeDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Всі", Value = "Book", Selected = true},
				new SelectListItem {Text = "Підручники", Value = "StudyBook", Selected = false},
				new SelectListItem {Text = "Додаткова література", Value = "AdditionalBook", Selected = false}
			};
		}

		// GET: Inventories
		public async Task<IActionResult> Index()
		{
			var applicationDbContext = _context.Inventories.Include(i => i.Book);

			ViewData["bookTypesList"] = _bookTypeDropdownList;

			ViewBag.InvCount = await _context.Inventories.CountAsync();
			ViewBag.StudyBooksInvCount = await _context.Inventories.CountAsync(i => i.Book.Discriminator == "StudyBook");
			ViewBag.AddBooksInvCount = await _context.Inventories.CountAsync(i => i.Book.Discriminator == "AdditionalBook");

			return View(await applicationDbContext.ToListAsync());
		}

		public async Task<IActionResult> Search
		(
			string type,
			int? bookId,
			short? year,
			int? actNumber,
			string couse,
			string note
		)
		{
			var inventories = _context.Inventories.Include(i => i.Book).AsQueryable();

			if (type != "Book")
				inventories = inventories.Where(i => i.Book.Discriminator == type);

			if (bookId.HasValue)
				inventories = inventories.Where(i => i.BookId == bookId);

			if (year.HasValue)
				inventories = inventories.Where(i => i.Year == year);

			if (actNumber.HasValue)
				inventories = inventories.Where(i => i.ActNumber == actNumber);

			if (!string.IsNullOrWhiteSpace(couse))
				inventories = inventories.Where(i => i.Couse == couse);

			if (!string.IsNullOrWhiteSpace(note))
				inventories = inventories.Where(i => i.Note == note);

			return PartialView("_Inventories", await inventories.ToListAsync());
		}

		// GET: Inventories/Details/5
		public async Task<IActionResult> Details(int? id, int? bookId)
		{
			if (id == null)
			{
				if (bookId != null)
					return RedirectToAction("Create", new {bookId});
				return NotFound();
			}

			var inventory = await _context.Inventories
				.Include(i => i.Book)
				.SingleOrDefaultAsync(m => m.Id == id);
			if (inventory == null)
				return NotFound();

			return View(inventory);
		}

		// GET: Inventories/Create
		[HttpGet]
		public IActionResult Create(int? bookId)
		{
			ViewData["BookId"] = bookId;
			return View();
		}

		// POST: Inventories/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,ActNumber,Year,Couse,Note,BookId")] Inventory inventory)
		{
			if (!_context.Books.Any(b => b.Id == inventory.BookId))
			{
				ModelState.AddModelError("BookId", "Книги з даним інвентарним номером не існує");
			}
			else if (_context.Inventories.Any(i => i.BookId == inventory.BookId))
			{
				ModelState.AddModelError("BookId", "Книга з даним інвентарним номером вже має інвентарний запис");
			}

			if (ModelState.IsValid)
			{
				inventory.Book = _context.Books.SingleOrDefault(b => b.Id == inventory.BookId);
				_context.Add(inventory);
				await _context.SaveChangesAsync();
				return RedirectToAction("Index");
			}

			ViewData["BookId"] = inventory.BookId;
			ViewData["Fail"] = true;

			return View(inventory);
		}

		// GET: Inventories/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var inventory = await _context.Inventories.SingleOrDefaultAsync(m => m.Id == id);
			if (inventory == null)
			{
				return NotFound();
			}
			return View(inventory);
		}

		// POST: Inventories/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, int curBookId,
			[Bind("Id,ActNumber,Year,Couse,Note,BookId")] Inventory inventory)
		{
			if (id != inventory.Id)
				return NotFound();

			if (!_context.Books.Any(b => b.Id == inventory.BookId))
				ModelState.AddModelError("BookId", "Книги з даним інвентарним номером не існує");

			if (_context.Inventories.Any(i => i.BookId == inventory.BookId && i.BookId != curBookId))
				ModelState.AddModelError("BookId", "Книга з даним інвентарним номером вже має інвентарний запис");

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(inventory);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!InventoryExists(inventory.Id))
						return NotFound();

					throw;
				}

				return RedirectToAction("Index");
			}

			inventory.BookId = curBookId;

			return View(inventory);
		}

		// GET: Inventories/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
				return NotFound();

			var inventory = await _context.Inventories
				.Include(i => i.Book)
				.SingleOrDefaultAsync(m => m.Id == id);

			if (inventory == null)
				return NotFound();

			return View(inventory);
		}

		// POST: Inventories/Delete/5
		[HttpPost]
		[ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var inventory = await _context.Inventories.SingleOrDefaultAsync(m => m.Id == id);
			_context.Inventories.Remove(inventory);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}

		private bool InventoryExists(int id)
		{
			return _context.Inventories.Any(e => e.Id == id);
		}
	}
}

SchoolLib/Controllers/ReadersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolLib.Data;
using SchoolLib.Models.People;

namespace SchoolLib.Controllers
{
	public class ReadersController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly List<SelectListItem> _readerStatusDropdownList;
		private readonly List<SelectListItem> _readerTypeDropdownList;

		public ReadersController(ApplicationDbContext context)
		{
			_context = context;

			_readerTypeDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Неважливо", Value = "Reader", Selected = true},
				new SelectListItem {Text = "Учень", Value = "Student", Selected = false},
				new SelectListItem {Text = "Співробітник", Value = "Worker", Selected = false}
			};

			_readerStatusDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Неважливо", Value = "Any", Selected = true},
				new SelectListItem {Text = "Активний", Value = "Enabled", Selected = false},
				new SelectListItem {Text = "Деактивований", Value = "Disabled", Selected = false},
				new SelectListItem {Text = "Вибув", Value = "Removed", Selected = false}
			};
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			ViewData["readerTypeList"] = _readerTypeDropdownList;
			ViewData["readerStatusList"] = _readerStatusDropdownList;

			ViewBag.StudentsCount = await _context.Students.CountAsync();
			ViewBag.WorkersCount = await _context.Workers.CountAsync();
			ViewBag.ReadersCount = await _context.Readers.CountAsync();

			return View();
		}

		public async Task<IActionResult> SearchActions(
			string type,
			int? id,
			string firstName,
			string surName,
			string patronimic,
			string street,
			string house,
			short? apartment,
			string note,
			ReaderStatus status,
			string actn)
		{
			List<Reader> readersList;
			var readers = _context.Readers.Where(r => status.HasFlag(r.Status));
			if (type != "Reader")
				readers = readers.Where(r => r.Discriminator == type);
			if (id.HasValue)
				readers = readers.Where(r => r.Id == id);
			if (!string.IsNullOrWhiteSpace(firstName))
				readers = readers.Where(r => r.FirstName == firstName);
			if (!string.IsNullOrWhiteSpace(surName))
				readers = readers.Where(r => r.SurName == surName);
			if (!string.IsNullOrWhiteSpace(patronimic))
				readers = readers.Where(r => r.Patronimic == patronimic);
			if (!string.IsNullOrWhiteSpace(street))
				readers = readers.Where(r => r.Street == street);
			if (!string.IsNullOrWhiteSpace(house))
				readers = readers.Where(r => r.House == house);
			if (apartment.HasValue)
				readers = readers.Where(r => r.Apartment == apartment);
			if (!string.IsNullOrWhiteSpace(note))
				readers = readers.Where(r => r.Note == note);

			ViewData["type"] = type == "Reader" ? typeof(Reader) : type == "Student" ? typeof(Student) : typeof(Worker);
			if (actn == "activate")
			{
				readersList = await readers.Where(r => r.Status == ReaderStatus.Disabled).ToListAsync();
				foreach (var r in readersList)
				{
					r.Status = ReaderStatus.Enabled;
					r.LastRegistrationDate = DateTime.Today.ToString("dd.MM.yyyy");
				}
				_context.UpdateRange(readersList);
				await _context.SaveChangesAsync();
			}
			else if (actn == "restore")
			{
				readersList = await readers.Where(r => r.Status == ReaderStatus.Removed).ToListAsync();
				foreach (var r in readersList)
				{
					r.Drop.Note = $"Відновлений {DateTime.Today.ToString("dd.MM.yyyy")}";
					r.Status = ReaderStatus.Disabled;
					r.LastRegistrationDate = DateTime.Today.ToString("dd.MM.yyyy");
				}
				_context.UpdateRange(readersList);
				await _context.SaveChangesAsync();
			}
			readersList = await readers.ToListAsync();
			return PartialView("_Readers", readersList);
		}

		public async Task<IActionResult> Activate(
			string type,
			int? id,
			string firstName,
			string surName,
			string patronimic,
			string street,
			string house,
			short? apartment,
			string lastRegDate,
			string firstRegDate,
			string note,
			ReaderStatus status)
		{
			var readers = _context.Readers.Where(r => status.HasFlag(r.Status));
			if (type != "Reader")
				readers = readers.Where(r => r.Discriminator == type);
			if (id.HasValue)
				readers = readers.Where(r => r.Id == id);
			if (!string.IsNullOrWhiteSpace(firstName))
				readers = readers.Where(r => r.FirstName == firstName);
			if (!string.IsNullOrWhiteSpace(surName))
				readers = readers.Where(r => r.SurName == surName);
			if (!string.IsNullOrWhiteSpace(patronimic))
				readers = readers.Where(r => r.Patronimic == patronimic);
			if (!string.IsNullOrWhiteSpace(street))
				readers = readers.Where(r => r.Street == street);
			if (!string.IsNullOrWhiteSpace(house))
				readers = readers.Where(r => r.House == house);
			if (apartment.HasValue)
				readers = readers.Where(r => r.Apartment == apartment);
			/* !todo:Исправить сравнение строк на сравнение дат */
			if (!string.IsNullOrWhiteSpace(lastRegDate))
				readers = readers.Where(r => r.LastRegistrationDate == lastRegDate);
			if (!string.IsNullOrWhiteSpace(firstRegDate))
				readers = readers.Where(r => r.FirstRegistrationDate == firstRegDate);
			/* !todo */
			if (!string.IsNullOrWhiteSpace(note))
				readers = readers.Where(r => r.Note == note);

			var view = "";

			return PartialView(view, await readers.ToListAsync());
		}

		// GET: Readers/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var reader = await _context.Readers
				.SingleOrDefaultAsync(m => m.Id == id);
			if (reader == null)
			{
				return NotFound();
			}
			if (reader.Discriminator == "Student")
			{
				return RedirectToAction("Details", "Students", new {id});
			}

			return RedirectToAction("Details", "Workers", new {id});
		}

		// GET: Readers/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var reader = await _context.Readers.SingleOrDefaultAsync(m => m.Id == id);
			if (reader == null)
			{
				return NotFound();
			}
			if (reader.Discriminator == "Student")
			{
				return RedirectToAction("Edit", "Students", new {id});
			}

			return RedirectToAction("Edit", "Workers", new {id});
		}

		// GET: Readers/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var reader = await _context.Readers
				.SingleOrDefaultAsync(m => m.Id == id);
			if (reader == null)
			{
				return NotFound();
			}
			if (reader.Discriminator == "Student")
			{
				return RedirectToAction("Delete", "Students", new {id});
			}

			return RedirectToAction("Delete", "Workers", new {id});
		}

		private bool ReaderExists(int id)
		{
			return _context.Readers.Any(e => e.Id == id);
		}
	}
}

SchoolLib/Views/StudyBooks/Create.cshtml
@model SchoolLib.Models.Books.StudyBook

@{
    ViewData["Title"] = "Додавання підручника";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>@Html.DisplayNameFor(m => m)</h4>
        <hr/>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Id" class="col-md-2 control-label"></label>*
            <div class="col-md-10">
                <input asp-for="Id" class="form-control" value="@ViewBag.FreeId"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Grade" class="col-md-2 control-label"></label>*
            <div class="col-md-10">
                <input asp-for="Grade" class="form-control"/>
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Subject" class="col-md-2 control-label"></label>*
            <div class="col-md-10">
                <input asp-for="Subject" class="form-control"/>
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Author" class="col-md-2 control-label"></label>*
            <div class="col-md-10">
                <input asp-for="Author" class="form-control"/>
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AuthorCipher" class="col-md-2 control-label"></label>*
            <div class="col-md-10">
                <input asp-for="AuthorCipher" class="form-control"/>
                <span asp-validation-for="AuthorCipher" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>*
            <div class="col-md-10">
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Published" class="col-md-2 control-label"></label>*
            <div class="col-md-10">
                <input asp-for="Published" class="form-control"/>
                <span asp-validation-for="Published" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>*
            <div class="col-md-10">
                <input asp-for="Price" class="form-control"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Note" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Note" class="form-control"/>
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Додати" class="btn btn-default"/>
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-controller="Books" asp-action="Index">Повернутися до списку</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

SchoolLib/Views/StudyBooks/Delete.cshtml
@using SchoolLib.Models.Books
@model SchoolLib.Models.Books.StudyBook

@{
    ViewData["Title"] = "Видалення підручника";
}

<h2>@ViewData["Title"]</h2>

<h3>Ви впевнені в тому, що бажаєте видалити цей підручник?</h3>
<div>
    <h4>@Html.DisplayNameFor(model => model)</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Id)</dt>
        <dd>@Html.DisplayFor(model => model.Id)</dd>

        <dt>@Html.DisplayNameFor(model => model.Grade)</dt>
        <dd>@Html.DisplayFor(model => model.Grade)</dd>

        <dt>@Html.DisplayNameFor(model => model.Subject)</dt>
        <dd>@Html.DisplayFor(model => model.Subject)</dd>

        <dt>@Html.DisplayNameFor(model => model.Author)</dt>
        <dd>@Html.DisplayFor(model => model.Author)</dd>

        <dt>@Html.DisplayNameFor(model => model.AuthorCipher)</dt>
        <dd>@Html.DisplayFor(model => model.AuthorCipher)</dd>

        <dt>@Html.DisplayNameFor(model => model.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Name)</dd>

        <dt>@Html.DisplayNameFor(model => model.Published)</dt>
        <dd>@Html.DisplayFor(model => model.Published)</dd>

        <dt>@Html.DisplayNameFor(model => model.Price)</dt>
        <dd>@Html.DisplayFor(model => model.Price)</dd>

        <dt>@Html.DisplayNameFor(model => model.Note)</dt>
        <dd>@Html.DisplayFor(model => model.Note)</dd>

        <dt>@Html.DisplayNameFor(model => model.Status)</dt>
    </dl>
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Видалити" class="btn btn-default"/> |
            <a asp-controller="Books" asp-action="Index">Повернутися до списку</a>
        </div>
    </form>
</div>

SchoolLib/Views/StudyBooks/Details.cshtml
@using SchoolLib.Models.Books
@model SchoolLib.Models.Books.StudyBook

@{
    ViewData["Title"] = "Деталі";
    if (Model.Status == BookStatus.OnHands)
    {
    }
}

<h2>@ViewData["Title"]</h2>

<div>
    <h4>@Html.DisplayNameFor(model => model)</h4>
    <p>
        <a asp-controller="Inventories" asp-action="Details" asp-route-id="@Model.Inventory?.Id" asp-route-bookId="@Model.Id" class="btn btn-default">Інвентаризація</a>
        <a asp-controller="Provenances" asp-action="Details" asp-route-id="@Model.Provenance?.Id" asp-route-bookId="@Model.Id" class="btn btn-default">Походження</a>
        <a asp-controller="Issuances" asp-action="Details" asp-route-bookId="@Model.Id" class="btn btn-default">Видача</a>
    </p>
    <hr/>
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Id)</dt>
        <dd>@Html.DisplayFor(model => model.Id)</dd>

        <dt>@Html.DisplayNameFor(model => model.Grade)</dt>
        <dd>@Html.DisplayFor(model => model.Grade)</dd>

        <dt>@Html.DisplayNameFor(model => model.Subject)</dt>
        <dd>@Html.DisplayFor(model => model.Subject)</dd>

        <dt>@Html.DisplayNameFor(model => model.Author)</dt>
        <dd>@Html.DisplayFor(model => model.Author)</dd>

        <dt>@Html.DisplayNameFor(model => model.AuthorCipher)</dt>
        <dd>@Html.DisplayFor(model => model.AuthorCipher)</dd>

        <dt>@Html.DisplayNameFor(model => model.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Name)</dd>

        <dt>@Html.DisplayNameFor(model => model.Published)</dt>
        <dd>@Html.DisplayFor(model => model.Published)</dd>

        <dt>@Html.DisplayNameFor(model => model.Price)</dt>
        <dd>@Html.DisplayFor(model => model.Price)</dd>

        <dt>@Html.DisplayNameFor(model => model.Note)</dt>
        <dd>@Html.DisplayFor(model => model.Note)</dd>

        <dt>@Html.DisplayNameFor(model => model.Status)</dt>
        <dd>
            @if (ViewBag.readerId != null)
            {
                <a asp-controller="Readers" asp-action="Details" asp-route-id="@ViewBag.readerId">
                    @Html.DisplayFor(model => model.Status)
                </a>
            }
            else
            {
                @Html.DisplayFor(model => model.Status)
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Редагувати</a> |
    <a asp-controller="Books" asp-action="Index">Повернутися до списку</a>
</div>