SchoolLib/Controllers/BooksController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolLib.Data;
using SchoolLib.Models.Books;

namespace SchoolLib.Controllers
{
	public class BooksController : Controller
	{
		private readonly List<SelectListItem> _bookStatusDropdownList;
		private readonly List<SelectListItem> _bookTypeDropdownList;
		private readonly ApplicationDbContext _context;

		public BooksController(ApplicationDbContext context)
		{
			_context = context;

			_bookTypeDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Всі", Value = "Book", Selected = true},
				new SelectListItem {Text = "Підручники", Value = "StudyBook", Selected = false},
				new SelectListItem {Text = "Додаткова література", Value = "AdditionalBook", Selected = false}
			};

			_bookStatusDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Неважливо", Value = "Any", Selected = true},
				new SelectListItem {Text = "В бібліотеці", Value = "InStock", Selected = false},
				new SelectListItem {Text = "У читача", Value = "OnHands", Selected = false}
			};
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			ViewData["bookTypesList"] = _bookTypeDropdownList;
			ViewData["bookStatusList"] = _bookStatusDropdownList;

			ViewBag.BooksCount = await _context.Books.CountAsync();
			ViewBag.AddBooksCount = await _context.AdditionalBooks.CountAsync();
			ViewBag.StudyBooksCount = await _context.StudyBooks.CountAsync();

			return View();
		}

		public async Task<IActionResult> Search(
			string type,
			int? id,
			string name,
			string author,
			BookStatus status)
		{
			var books = _context.Books.Where(b => status.HasFlag(b.Status));
			if (type != "Book")
				books = books.Where(b => b.Discriminator == type);
			if (id.HasValue)
				books = books.Where(b => b.Id == id);
			if (!string.IsNullOrWhiteSpace(name))
				books = books.Where(b => b.Name == name);
			if (!string.IsNullOrWhiteSpace(author))
				books = books.Where(b => b.Author == author);

			ViewData["type"] = type == "Book" ? typeof(Book) : type == "StudyBook" ? typeof(StudyBook) : typeof(AdditionalBook);

			return PartialView("_Books", await books.ToListAsync());
		}

		// GET: Books/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var book = await _context.Books
				.SingleOrDefaultAsync(m => m.Id == id);
			if (book == null)
			{
				return NotFound();
			}

			if (book.Discriminator == "AdditionalBook")
			{
				return RedirectToAction("Details", "AdditionalBooks", new {id});
			}

			return RedirectToAction("Details", "StudyBooks", new {id});
		}

		// GET: Readers/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var book = await _context.Books.SingleOrDefaultAsync(m => m.Id == id);

			if (book == null)
			{
				return NotFound();
			}

			if (book.Discriminator == "AdditionalBook")
			{
				return RedirectToAction("Edit", "AdditionalBooks", new {id});
			}

			return RedirectToAction("Edit", "StudyBooks", new {id});
		}

		// GET: Readers/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var book = await _context.Books.SingleOrDefaultAsync(m => m.Id == id);

			if (book == null)
			{
				return NotFound();
			}

			if (book.Discriminator == "AdditionalBook")
			{
				return RedirectToAction("Delete", "AdditionalBooks", new {id});
			}

			return RedirectToAction("Delete", "StudyBooks", new {id});
		}
	}
}

SchoolLib/Controllers/DropsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolLib.Data;
using SchoolLib.Models.People;

namespace SchoolLib.Controllers
{
	public class DropsController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly List<SelectListItem> _readerTypeDropdownList;

		public DropsController(ApplicationDbContext context)
		{
			_context = context;
			_readerTypeDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Неважливо", Value = "Reader", Selected = true},
				new SelectListItem {Text = "Учень", Value = "Student", Selected = false},
				new SelectListItem {Text = "Співробітник", Value = "Worker", Selected = false}
			};
		}

		public async Task<IActionResult> Index()
		{
			var applicationDbContext = _context.Drops.Include(d => d.Reader);

			ViewData["readerTypeList"] = _readerTypeDropdownList;
			ViewBag.DropsCount = await _context.Drops.CountAsync();
			ViewBag.StudentsDropsCount = await _context.Drops.CountAsync(d => d.Reader.Discriminator.Equals("Student"));
			ViewBag.WorkersDropsCount = await _context.Drops.CountAsync(d => d.Reader.Discriminator.Equals("Worker"));

			return View(await applicationDbContext.ToListAsync());
		}

		public async Task<IActionResult> Search
		(
			string type,
			int? readerId,
			string date,
			string couse,
			string note
		)
		{
			var drops = _context.Drops.Include(d => d.Reader).AsQueryable();

			if (type != "Reader")
				drops = drops.Where(d => d.Reader.Discriminator == type);

			if (readerId.HasValue)
				drops = drops.Where(d => d.ReaderId == readerId);

			if (!string.IsNullOrWhiteSpace(date))
				drops = drops.Where(d => d.Date == date);

			if (!string.IsNullOrWhiteSpace(couse))
				drops = drops.Where(d => d.Couse == couse);

			if (!string.IsNullOrWhiteSpace(note))
				drops = drops.Where(d => d.Note == note);

			return PartialView("_Drops", await drops.ToListAsync());
		}

		public async Task<IActionResult> Details(int? id, int? readerId)
		{
			if (id == null)
			{
				if (readerId != null)
					return RedirectToAction("Create", new {readerId});
				return NotFound();
			}
			var drop = await _context.Drops
				.Include(d => d.Reader)
				.SingleOrDefaultAsync(m => m.Id == id);
			if (drop == null)
				return NotFound();
			return View(drop);
		}

		[HttpGet]
		public IActionResult Create(int? readerId)
		{
			Reader reader =
				_context.Students.SingleOrDefault(r => r.Id == readerId) ??
				(Reader) _context.Workers.SingleOrDefault(r => r.Id == readerId);

			ViewData["Reader"] = reader;
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Date,Couse,Note,ReaderId")] Drop drop)
		{
			if (!_context.Readers.Any(b => b.Id == drop.ReaderId))
			{
				ModelState.AddModelError("ReaderId", "Читача з даним ідентифікаційним номером не існує");
				ViewData["Fail"] = true;
			}
			else if (_context.Drops.Any(d => d.ReaderId == drop.ReaderId))
			{
				ModelState.AddModelError("ReaderId", "Читач з даним ідентифікаційним номером вже має запис про вибуття");
				ViewData["Fail"] = true;
			}
			if (ModelState.IsValid)
			{
				_context.Add(drop);
				await _context.SaveChangesAsync();
				await DropReader(drop.ReaderId);
				return RedirectToAction("Index");
			}
			ViewData["ReaderId"] = drop.ReaderId;
			return View(drop);
		}

		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
				return NotFound();
			var drop = await _context.Drops.SingleOrDefaultAsync(m => m.Id == id);
			if (drop == null)
				return NotFound();
			ViewData["ReaderId"] = drop.ReaderId;
			return View(drop);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit
		(
			int id,
			int curReaderId,
			[Bind("Id,Date,Couse,Note,ReaderId")] Drop drop
		)
		{
			if (id != drop.Id)
				return NotFound();
			if (!_context.Readers.Any(b => b.Id == drop.ReaderId))
				ModelState.AddModelError("ReaderId", "Читача з даним ідентифікаційним номером не існує");
			else if (_context.Drops.Any(d => d.ReaderId == drop.ReaderId && d.ReaderId != curReaderId))
				ModelState.AddModelError("ReaderId", "Читач з даним ідентифікаційним номером вже має запис про вибуття");
			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(drop);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!DropExists(drop.Id))
						return NotFound();
					throw;
				}
				return RedirectToAction("Index");
			}
			drop.ReaderId = curReaderId;
			return View(drop);
		}

		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
				return NotFound();
			var drop = await _context.Drops
				.Include(d => d.Reader)
				.SingleOrDefaultAsync(m => m.Id == id);
			if (drop == null)
				return NotFound();
			return View(drop);
		}

		[HttpPost]
		[ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var drop = await _context.Drops.SingleOrDefaultAsync(m => m.Id == id);
			_context.Drops.Remove(drop);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}

		private bool DropExists(int id)
		{
			return _context.Drops.Any(e => e.Id == id);
		}

		private async Task<int> DropReader(int id)
		{
			var reader = await _context.Readers.Include(d => d.Drop)
				.SingleOrDefaultAsync(m => m.Id == id);
			reader.Status = ReaderStatus.Removed;
			_context.Update(reader);
			return await _context.SaveChangesAsync();
		}
	}
}

SchoolLib/Controllers/ReadersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolLib.Data;
using SchoolLib.Models.People;

namespace SchoolLib.Controllers
{
	public class ReadersController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly List<SelectListItem> _readerStatusDropdownList;
		private readonly List<SelectListItem> _readerTypeDropdownList;

		public ReadersController(ApplicationDbContext context)
		{
			_context = context;

			_readerTypeDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Неважливо", Value = "Reader", Selected = true},
				new SelectListItem {Text = "Учень", Value = "Student", Selected = false},
				new SelectListItem {Text = "Співробітник", Value = "Worker", Selected = false}
			};

			_readerStatusDropdownList = new List<SelectListItem>
			{
				new SelectListItem {Text = "Неважливо", Value = "Any", Selected = true},
				new SelectListItem {Text = "Активний", Value = "Enabled", Selected = false},
				new SelectListItem {Text = "Деактивований", Value = "Disabled", Selected = false},
				new SelectListItem {Text = "Вибув", Value = "Removed", Selected = false}
			};
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			ViewData["readerTypeList"] = _readerTypeDropdownList;
			ViewData["readerStatusList"] = _readerStatusDropdownList;

			ViewBag.StudentsCount = await _context.Students.CountAsync();
			ViewBag.WorkersCount = await _context.Workers.CountAsync();
			ViewBag.ReadersCount = await _context.Readers.CountAsync();

			return View();
		}

		public async Task<IActionResult> SearchActions(
			string type,
			int? id,
			string firstName,
			string surName,
			string patronimic,
			string street,
			string house,
			short? apartment,
			string note,
			ReaderStatus status,
			string actn)
		{
			List<Reader> readersList;
			var readers = _context.Readers.Where(r => status.HasFlag(r.Status));
			if (type != "Reader")
				readers = readers.Where(r => r.Discriminator == type);
			if (id.HasValue)
				readers = readers.Where(r => r.Id == id);
			if (!string.IsNullOrWhiteSpace(firstName))
				readers = readers.Where(r => r.FirstName == firstName);
			if (!string.IsNullOrWhiteSpace(surName))
				readers = readers.Where(r => r.SurName == surName);
			if (!string.IsNullOrWhiteSpace(patronimic))
				readers = readers.Where(r => r.Patronimic == patronimic);
			if (!string.IsNullOrWhiteSpace(street))
				readers = readers.Where(r => r.Street == street);
			if (!string.IsNullOrWhiteSpace(house))
				readers = readers.Where(r => r.House == house);
			if (apartment.HasValue)
				readers = readers.Where(r => r.Apartment == apartment);
			if (!string.IsNullOrWhiteSpace(note))
				readers = readers.Where(r => r.Note == note);

			ViewData["type"] = type == "Reader" ? typeof(Reader) : type == "Student" ? typeof(Student) : typeof(Worker);
			if (actn == "activate")
			{
				readersList = await readers.Where(r => r.Status == ReaderStatus.Disabled).ToListAsync();
				foreach (var r in readersList)
				{
					r.Status = ReaderStatus.Enabled;
					r.LastRegistrationDate = DateTime.Today.ToString("dd.MM.yyyy");
				}
				_context.UpdateRange(readersList);
				await _context.SaveChangesAsync();
			}
			else if (actn == "restore")
			{
				readersList = await readers.Where(r => r.Status == ReaderStatus.Removed).ToListAsync();
				foreach (var r in readersList)
				{
					r.Drop.Note = $"Відновлений {DateTime.Today.ToString("dd.MM.yyyy")}";
					r.Status = ReaderStatus.Disabled;
					r.LastRegistrationDate = DateTime.Today.ToString("dd.MM.yyyy");
				}
				_context.UpdateRange(readersList);
				await _context.SaveChangesAsync();
			}
			readersList = await readers.ToListAsync();
			return PartialView("_Readers", readersList);
		}

		public async Task<IActionResult> Activate(
			string type,
			int? id,
			string firstName,
			string surName,
			string patronimic,
			string street,
			string house,
			short? apartment,
			string lastRegDate,
			string firstRegDate,
			string note,
			ReaderStatus status)
		{
			var readers = _context.Readers.Where(r => status.HasFlag(r.Status));
			if (type != "Reader")
				readers = readers.Where(r => r.Discriminator == type);
			if (id.HasValue)
				readers = readers.Where(r => r.Id == id);
			if (!string.IsNullOrWhiteSpace(firstName))
				readers = readers.Where(r => r.FirstName == firstName);
			if (!string.IsNullOrWhiteSpace(surName))
				readers = readers.Where(r => r.SurName == surName);
			if (!string.IsNullOrWhiteSpace(patronimic))
				readers = readers.Where(r => r.Patronimic == patronimic);
			if (!string.IsNullOrWhiteSpace(street))
				readers = readers.Where(r => r.Street == street);
			if (!string.IsNullOrWhiteSpace(house))
				readers = readers.Where(r => r.House == house);
			if (apartment.HasValue)
				readers = readers.Where(r => r.Apartment == apartment);
			/* !todo:Исправить сравнение строк на сравнение дат */
			if (!string.IsNullOrWhiteSpace(lastRegDate))
				readers = readers.Where(r => r.LastRegistrationDate == lastRegDate);
			if (!string.IsNullOrWhiteSpace(firstRegDate))
				readers = readers.Where(r => r.FirstRegistrationDate == firstRegDate);
			/* !todo */
			if (!string.IsNullOrWhiteSpace(note))
				readers = readers.Where(r => r.Note == note);

			var view = "";

			return PartialView(view, await readers.ToListAsync());
		}

		// GET: Readers/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var reader = await _context.Readers
				.SingleOrDefaultAsync(m => m.Id == id);
			if (reader == null)
			{
				return NotFound();
			}
			if (reader.Discriminator == "Student")
			{
				return RedirectToAction("Details", "Students", new {id});
			}

			return RedirectToAction("Details", "Workers", new {id});
		}

		// GET: Readers/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var reader = await _context.Readers.SingleOrDefaultAsync(m => m.Id == id);
			if (reader == null)
			{
				return NotFound();
			}
			if (reader.Discriminator == "Student")
			{
				return RedirectToAction("Edit", "Students", new {id});
			}

			return RedirectToAction("Edit", "Workers", new {id});
		}

		// GET: Readers/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var reader = await _context.Readers
				.SingleOrDefaultAsync(m => m.Id == id);
			if (reader == null)
			{
				return NotFound();
			}
			if (reader.Discriminator == "Student")
			{
				return RedirectToAction("Delete", "Students", new {id});
			}

			return RedirectToAction("Delete", "Workers", new {id});
		}

		private bool ReaderExists(int id)
		{
			return _context.Readers.Any(e => e.Id == id);
		}
	}
}

SchoolLib/Views/Shared/_Layout.cshtml
@using Microsoft.ApplicationInsights.AspNetCore
@inject JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SchoolLib</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Навігаційний перемикач</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                <strong>SchoolLib</strong>
            </a>
        </div>
        <div class="navbar-collapse collapse">
            @await Html.PartialAsync("_LoginPages")
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </div>
</nav>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <ul class="breadcrumb">
            <li style="display: inline; margin: 0 20px 20px 0;">&copy; 2017 - SchoolLib</li>
            <li style="display: inline; margin: 0 20px 20px 0;">
                <a asp-area="" asp-controller="Home" asp-action="About">Довідка</a>
            </li>
            <li style="display: inline; margin: 0 20px 20px 0;">
                <a asp-area="" asp-controller="Home" asp-action="Contact">Контакти</a>
            </li>
        </ul>
    </footer>
</div>

<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>
@RenderSection("Scripts", false)
</body>
</html>

SchoolLib/Views/Shared/_LoginPages.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<ul class="nav navbar-nav nav-tabs">
    @if (SignInManager.IsSignedIn(User))
    {
        <li>
            <a asp-area="" asp-controller="Books" asp-action="Index">
                <img src="~/images/book-solid.png" class="img-rounded" style="height: 30px; width: 30px !important">
                @*<span class="glyphicon glyphicon-book"></span>*@
                <strong>Книги</strong>
            </a>
        </li>
        @*<li><a asp-area="" asp-controller="Issuances" asp-action="Index">Видача</a></li>*@
        <li>
            <a asp-area="" asp-controller="Readers" asp-action="Index">
                <img src="~/images/many-people-solid.png" class="img-rounded" style="height: 30px; width: 30px !important">
                <strong>Читачі</strong>
            </a>
        </li>

        @*<li><a asp-area="" asp-controller="Inventories" asp-action="Index">Інвентаризація</a></li>
        <li><a asp-area="" asp-controller="Provenances" asp-action="Index">Походження</a></li>
        <li><a asp-area="" asp-controller="Drops" asp-action="Index">Вибуття</a></li>*@
    }
    <li>
        <a asp-area="" asp-controller="Statistic" asp-action="Index">
            <img src="~/images/statistic.png" class="img-rounded" style="height: 30px; width: 30px !important">
            <strong>Статистика</strong>
        </a>
    </li>

</ul>